# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            JayBee
url:              https://www.jaybee.cz
baseurl:

author:
  name:           'Jan Breuer'
  url:            http://www.jaybee.cz

# paginate:         10
# paginate_path:    "/posts/page:num/"

github:
  repo:           https://github.com/j123b567

collections:
  software:
    output: true
    permalink: /software/:path/

defaults:
 - scope:
     path: ""
     type: software
   values:
     layout: page
